#! /usr/bin/perl -w

use strict;

use Net::SNMP;


my $hostip=$ARGV[0];

my ($session, $error) = Net::SNMP->session(
   -hostname  => shift || $hostip,
   -community => shift || 'public',
   -port      => shift || 161 
);

if (!defined($session)) {
   printf("ERROR: %s.\n", $error);
   exit 1;
}

my $tempbat = '1.3.6.1.4.1.318.1.1.1.2.2.2.0';

my $result = $session->get_request(
   -varbindlist => [$tempbat]
);

if (!defined($result)) {
   printf("ERROR: %s.\n", $session->error);
   $session->close;
   exit 2;
}

my $temp_value = $result->{$tempbat};
my $perf="temp=%s;40;64;-50;100;";

if ($temp_value >64) {
    printf("CRIT: Fire!!! Temperature of batteries: $temp_value |".$perf."\n",$temp_value);
    exit 2;
    }
if ($temp_value >40) {
    printf("WARN: I'm not hotdog!!! Temperature of batteries: $temp_value |".$perf."\n",$temp_value);
    exit 1;
    }
if ($temp_value <=1) {
    printf("CRIT: I'm frozen! Temperature of batteries: $temp_value |".$perf."\n",$temp_value);
    exit 2;
    }
printf("OK: Temperature of batteries: $temp_value C|".$perf."\n",$temp_value);
exit 0;

