#! /usr/bin/perl -w

use strict;

use Net::SNMP;


my $hostip=$ARGV[0];

my ($session, $error) = Net::SNMP->session(
   -hostname  => shift || $hostip,
   -community => shift || 'public',
   -port      => shift || 161 
);

if (!defined($session)) {
   printf("ERROR: %s.\n", $error);
   exit 1;
}

my $inputac = '1.3.6.1.4.1.318.1.1.1.3.2.1.0';

my $result = $session->get_request(
   -varbindlist => [$inputac]
);

if (!defined($result)) {
   printf("ERROR: %s.\n", $session->error);
   $session->close;
   exit 2;
}

my $perf="V=%s;180;260;0;380;";

if (($result->{$inputac} < 180) or $result->{$inputac} > 260) {
   printf("CRIT: Error input AC: %sV |".$perf."\n",$result->{$inputac},$result->{$inputac});
   $session->close;
   exit 2;
}

printf("OK: Input AC: %sV |".$perf."\n",$result->{$inputac},$result->{$inputac});
$session->close;
exit 0;
