#!/usr/bin/perl

use strict;

use Net::SNMP qw(ticks_to_time TRANSLATE_NONE);

my ($session, $error) = Net::SNMP->session(
   -hostname  => shift || '127.0.0.1',
   -community => shift || 'public',
   -port      => shift || 161,
   -version   => shift || '2'
);


if (!defined($session)) {
   printf("ERROR: %s.\n", $error);
   exit 1;
}

#sysUpTimeInstance .1.3.6.1.2.1.1.3.0

my $inputline = '.1.3.6.1.2.1.1.3.0';

$session->translate(TRANSLATE_NONE);

my $result = $session->get_request(
   -varbindlist => [$inputline]
);

if (!defined($result)) {
   printf("ERROR: %s.\n", $session->error);
   $session->close;
   exit 2;
}

$session->close;

my $value = $result->{$inputline};

my $uptime = ticks_to_time($value);

my $perf_data = "input=0;0;0;0;0;";
if (!defined($result->{$inputline})) {
    printf("ERROR: %s. |".$perf_data."\n", $session->error);
    $session->close;
    exit 2;
    }

$perf_data = "uptime=%s;0;0;0;0;";
if ($value <=480) {
    printf("ERROR: Restarted device! Uptime: %s |".$perf_data."\n", $uptime, $value);
    $session->close;
    exit 2;
    }

printf("OK Uptime: %s |".$perf_data."\n", $uptime,$value);

exit 0;
