#! /usr/bin/perl -w

use strict;

use Net::SNMP;


my $hostip=$ARGV[0];

my ($session, $error) = Net::SNMP->session(
   -hostname  => shift || $hostip,
   -community => shift || 'public',
   -port      => shift || 161
);

if (!defined($session)) {
   printf("ERROR: %s.\n", $error);
   exit 1;
}

my $inputline = '1.3.6.1.4.1.25728.8900.1.1.2.2';

my $result = $session->get_request(
   -varbindlist => [$inputline]
);

if (!defined($result)) {
   printf("ERROR: %s.\n", $session->error);
   $session->close;
   exit 2;
}

if ($result->{$inputline} == 0) {
   printf("ERROR Input Power!\n",$result->{$inputline});
   $session->close;
   exit 2;
}

printf("OK Input Power\n", $result->{$inputline});
$session->close;
exit 0;
