#! /usr/bin/perl -w

use strict;

use Net::SNMP;


my $hostip=$ARGV[0];

my ($session, $error) = Net::SNMP->session(
   -hostname  => shift || $hostip,
   -community => shift || 'public',
   -port      => shift || 161 
);

if (!defined($session)) {
   printf("ERROR: %s.\n", $error);
   exit 1;
}

my $inputac = '1.3.6.1.2.1.33.1.3.3.1.3.1';

my $result = $session->get_request(
   -varbindlist => [$inputac]
);

if (!defined($result)) {
   printf("ERROR: %s.\n", $session->error);
   $session->close;
   exit 2;
}

if (($result->{$inputac} < 201) or $result->{$inputac} > 255) {
   printf("ERROR Input AC: %sV\n",$result->{$inputac});
   $session->close;
   exit 2;
}

printf("OK Input AC %sV\n", $result->{$inputac});
$session->close;
exit 0;

