#! /usr/bin/perl -w

use strict;

use Net::SNMP;

my $hostip=$ARGV[0];

my ($session, $error) = Net::SNMP->session(
    -hostname  => shift || $hostip,
    -community => shift || 'public',
    -port      => shift || 161
);

if (!defined($session)) {
    printf("ERROR: %s.\n", $error);
    exit 1;
}

my $upsmod = '1.3.6.1.2.1.33.1.1.2.0';

my $result = $session->get_request(
    -varbindlist => [$upsmod]
);

if (!defined($result)) {
    printf("ERROR: %s.\n", $session->error);
    $session->close;
    exit 2;
}

printf("UPS model: %s\n", $result->{$upsmod});
$session->close;
exit 0;
