#!/usr/bin/perl

use strict;
use Net::SNMP qw(ticks_to_time TRANSLATE_NONE);

my $debug = 0;

my @ups_oids = (
#default
'.1.3.6.1.2.1.33.1.2.3',
#apc
'.1.3.6.1.4.1.318.1.1.1.2.2.3',
#eaton
'.1.3.6.1.4.1.534.1.2.1',
);

exit if (!$ARGV[0]);

my $hostip=$ARGV[0];

my ($session, $error) = Net::SNMP->session(
   -hostname  => shift || $hostip,
   -community => shift || 'public',
   -port      => shift || '161',
   -version   => shift || '1',
);

if (!defined($session)) { printf("ERROR: %s.\n", $error); exit 1; }

$session->translate(TRANSLATE_NONE);

my %result;
foreach my $key (@ups_oids) {
my $ret = $session->get_request( -varbindlist => [$key] );
my $value;
if (!$ret) {
    #search in subtree
    $ret = $session->get_next_request( -varbindlist => [$key] );
    my $branch = $key.'.*';
    my @keys_next = keys %$ret;
    my $get_key = $keys_next[0];
    if ($get_key=~/^$branch$/) {
	$value = $ret->{$get_key};
        print STDERR "Get-Next for key $key: $get_key => $value\n" if ($debug);
	}
    } else {
    $value = $ret->{$key};
    print STDERR "Get: $key => $value\n" if ($debug);
    }
next if (!defined($value));
$result{$key}=$value;
}
$session->close;

if (!%result) { printf("ERROR: Unknown model. Illegal oid list!\n"); exit 2; }

my $result_ok = 0;

my $perf_data = "remain=%sm;12;10;;;";
my $return_value;
my $online_min;
foreach my $key (keys %result) {
next if (!$key);
$return_value = $result{$key};
next if (!defined($return_value));
$result_ok = 1;

########### check space
#apc
if ($key eq $ups_oids[1]) { $online_min = int($return_value/6000); }
#eaton
if ($key eq $ups_oids[2]) { $online_min = int($return_value/60); }
#default
if ($key eq $ups_oids[0]) { $online_min = $return_value; }

print STDERR "$key => $online_min\n" if ($debug);

#compare
if ($online_min <= 8) {
    printf("ERROR! Before switching-off ups remains %s minutes |".$perf_data."\n", $online_min,$online_min);
    exit 2;
    }

if ($online_min > 8 and $online_min<=12) {
    printf("WARNING! Before switching-off ups remains %s minutes |".$perf_data."\n", $online_min,$online_min);
    exit 1;
    }
}

if ($result_ok) {
    #print OK
    printf("OK Before switching-off ups remains %s minutes |".$perf_data."\n", $online_min,$online_min);
    exit 0;
    }

printf("WARNING! You shouldn't have seen this. If you still see it, something clearly went wrong.\n");
exit 3;
