#! /usr/bin/perl -w

use strict;
use Net::SNMP;

my $hostip=$ARGV[0];

my ($session, $error) = Net::SNMP->session(
   -hostname  => shift || $hostip,
   -community => shift || 'public',
   -port      => shift || 161
);

if (!defined($session)) {
   printf("ERROR: %s.\n", $error);
   exit 1;
}

our %RAISECOM_MIBS = (
    'temperature'=>'.1.3.6.1.4.1.8886.1.1.4.2.1.0',
    'temperatureMin'=>'.1.3.6.1.4.1.8886.1.1.4.2.2.0',
    'temperatureMax'=>'.1.3.6.1.4.1.8886.1.1.4.2.3.0',
    );

my $ret = 0;

my $result = $session->get_request( -varbindlist => [$RAISECOM_MIBS{temperatureMax}]);

if (!$result) {
    print("ERROR: SNMP Error!\n");
    $session->close;
    exit 2;
    }

my $temp_max = $result->{$RAISECOM_MIBS{temperatureMax}};

$result = $session->get_request( -varbindlist => [$RAISECOM_MIBS{temperature}]);
my $temp_value = $result->{$RAISECOM_MIBS{temperature}};

$session->close;

my $perf="temp=%s;50;60;-50;100;";

if ($temp_value >$temp_max) {
    printf("CRIT: Fire!!! Temperature $temp_value |".$perf."\n",$temp_value);
    exit 2;
    }

if ($temp_value >50) {
    printf("WARN: I'm not hotdog!!! Temperature $temp_value |".$perf."\n",$temp_value);
    exit 1;
    }

if ($temp_value <=1) {
    printf("CRIT: I'm frozen! Temperature $temp_value |".$perf."\n",$temp_value);
    exit 2;
    }

printf("OK: Temp $temp_value C|".$perf."\n",$temp_value);
exit 0;
