#! /usr/bin/perl -w

use strict;
use Net::SNMP;

my $hostip=$ARGV[0];

my ($session, $error) = Net::SNMP->session(
   -hostname  => shift || $hostip,
   -community => shift || 'public',
   -port      => shift || 161
);

if (!defined($session)) {
   printf("ERROR: %s.\n", $error);
   exit 1;
}

our %RAISECOM_MIBS = (
    'PowerState'=>'.1.3.6.1.4.1.8886.1.24.2.1.1.5'
    );

my $ret = 1;

my $result_state = $session->get_table($RAISECOM_MIBS{PowerState});

for my $result_oid (keys %$result_state) {
my $power_state = $result_state->{$result_oid};
if ($power_state <=8000) {
	$ret = 2;
	my $power_index = $result_oid;
	$power_index =~ s/$RAISECOM_MIBS{PowerState}\.//;
	printf("ERROR Power $power_index fail ($power_state)!");
    } else { $ret = 0; }
}

$session->close;
if ($ret == 0) { print("OK Power\n"); } else { print "\n"; }
exit $ret;
