#! /usr/bin/perl -w

use strict;

use Net::SNMP;


my $hostip=$ARGV[0];

my ($session, $error) = Net::SNMP->session(
   -hostname  => shift || $hostip,
   -community => shift || 'public',
   -port      => shift || 161 
);

if (!defined($session)) {
   printf("ERROR: %s.\n", $error);
   exit 1;
}

my $curtemp = '1.3.6.1.4.1.890.1.5.8.26.9.2.1.2.3';
#my $maxtemp = '1.3.6.1.4.1.890.1.5.8.26.9.2.1.3.1';
#my $mintemp = '1.3.6.1.4.1.890.1.5.8.26.9.2.1.4.1';

my $result = $session->get_request(
   -varbindlist => [$curtemp]
);

if (!defined($result)) {
   printf("ERROR: %s.\n", $session->error);
   $session->close;
   exit 2;
}

if (($result->{$curtemp} < 0) or $result->{$curtemp} > 55) {
   printf("ERROR Current Temp: %s\n",$result->{$curtemp});
   $session->close;
   exit 2;
}

printf("OK Temperature current: %s\n", $result->{$curtemp});
$session->close;
exit 0;
