#!/bin/sh

### command line 1-Host 2-Community 3-port_num

### return codes
RET_OK=0
RET_WARNING=1
RET_UNKNOWN=3
RET_CRITICAL=2
IF_IDX=""

if [ -n "$1" -a "$2" -a "$3" -a "$4" ]; then
 for i in `seq 1 10`
 do
  snmp_w=`snmpget -v 2c -c $2 -O vqe $1 1.3.6.1.2.1.2.2.1.2.$i`
  val=$?
  if [ $val -eq 0 ]; then
    if [ "$snmp_w" != "No Such Instance currently exists at this OID" ]; then
	if  [ "$snmp_w" == "$3" ]; then
	    IF_IDX=$i
        fi
    fi
  else
    echo "SNMPGET error! $snmp_w"; exit $RET_UNKNOWN 
  fi
 done

 if [ -z "$IF_IDX" ]; then
    echo "Port $3 not found"; exit $RET_UNKNOWN
 fi

 snmp_w=`snmpget  -c $2 -v1 -O vqe $1 1.3.6.1.2.1.2.2.1.5.$IF_IDX`
 val=$?
 if [ $val -eq 0 ]; then
    if [ "$snmp_w" -eq "$4" ]; then
	echo "Speed OK: $snmp_w Index: $IF_IDX"
	exit $RET_OK
    else
	echo "Speed CRITICAL: $snmp_w != $4 Index: $IF_IDX"
	exit $RET_WARNING
    fi
 else
      echo "Wrong Parameters! $snmp_w"; exit $RET_UNKNOWN 
 fi

else
  echo "Bad Parameters!"; exit $RET_UNKNOWN
fi
