#! /usr/bin/perl -w

use strict;

use Net::SNMP;


my $hostip=$ARGV[0];

my ($session, $error) = Net::SNMP->session(
   -hostname  => shift || $hostip,
   -community => shift || 'public',
   -port      => shift || 161 
);

if (!defined($session)) {
   printf("ERROR: %s.\n", $error);
   exit 1;
}

my $batreplace = '1.3.6.1.4.1.318.1.1.1.2.2.4.0';

my $result = $session->get_request(
   -varbindlist => [$batreplace]
);

if (!defined($result)) {
   printf("ERROR: %s.\n", $session->error);
   $session->close;
   exit 2;
}

if ($result->{$batreplace} > 1) {
   print("ERROR!!! Battery requires replacement!\n");
   $session->close;
   exit 2;
}

printf("OK. No Battery requires replacement.\n");
$session->close;
exit 0;
