#!/bin/sh

### command line 1-Host 2-Community 3-port_num

### return codes
RET_OK=0
RET_WARNING=1
RET_UNKNOWN=3
RET_CRITICAL=2

if [ -n "$1" -a "$2" -a "$3" ]; then
 snmp_w=`snmpget  -c $2 -v1 -O vqe $1  1.3.6.1.2.1.2.2.1.8.$3 `
 val=$?
 if [ $val -eq 0 ]; then 
  if [ $snmp_w -eq 2 ]; then
    echo "Port $3 is DOWN! $snmp_w"; exit $RET_CRITICAL
   elif [ $snmp_w -eq 1 ]; then
    echo "Port $3 is UP! $snmp_w"; exit $RET_OK
   else
    echo "Port $3 state UNKNOWN! $snmp_w"; exit $RET_UNKNOWN   
  fi
 else
  echo "Wrong Parameters! $snmp_w"; exit $RET_UNKNOWN 
 fi 
else
 echo "Not Parameters! $snmp_w"; exit $RET_UNKNOWN
fi
